---
version: "3.8"
services:
  app:
    build: ./flask-app
    ports:
      - "5555:5000"
    container_name: flask_app
    restart: unless-stopped
  db:
    build: ./postgres-db
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ./postgres-db/.env
